node
{
   stage 'dev'
   sh 'echo "Build Start ........................................................................."'
   sh 'chmod 757 $WORKSPACE/*.sh'
   sh 'ssh bhagya@localhost mkdir -p $DEV_DESTINATION/'
   sh 'ssh bhagya@localhost chmod 757 $DEV_DESTINATION/'
   sh 'scp $WORKSPACE/*.sh bhagya@localhost:$DEV_DESTINATION/'
   sh 'echo "Build End............................................................................"'
   sh 'echo "Test Start..........................................................................."'
   sh 'ssh bhagya@localhost bash $DEV_DESTINATION/printn.sh 10'
   sh 'ssh bhagya@localhost bash $DEV_DESTINATION/tablen.sh 17'
   sh 'ssh bhagya@localhost bash $DEV_DESTINATION/primen.sh 10'
   sh 'ssh bhagya@localhost bash $DEV_DESTINATION/sort.sh 5 2 3 1 4'
   sh 'ssh bhagya@localhost bash $DEV_DESTINATION/compoundint.sh 100000 1y 12.4'
   sh 'ssh bhagya@localhost bash $DEV_DESTINATION/factorialn.sh 4'
   sh 'ssh bhagya@localhost bash $DEV_DESTINATION/a.sh 5'
   sh 'ssh bhagya@localhost bash $DEV_DESTINATION/b.sh'
   sh 'ssh bhagya@localhost bash $DEV_DESTINATION/c.sh'
   sh 'ssh bhagya@localhost bash $DEV_DESTINATION/d.sh'
   sh 'echo "Test End............................................................................."'
}
